---
- name: configuro servidor de base de datos en ubuntu
  hosts: database
  become: true
  user: sysadmin


  tasks:
  - name: UFW instalado
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: Permitir puerto 22 en ufw
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Defino politicas de trafico entrante
    community.general.ufw:
      policy: allow
      direction: outgoing
      state: enabled
 

  - name: Defino politicas de trafico entrante
    community.general.ufw:
      policy: deny
      direction: incoming
      state: enabled

  - name: servicio UFW lvantado y activo
    ansible.builtin.sistemd_service:
      name: ufw
      state: started
      enable: true

##  instalacion de base de datos
  - name: MariaDB instalado
    ansible.builtin.apt:
      name: mariadb-server
      state: present
      update-cache: true

  - name: Servidor Mariadb levantado
    ansible.builtin.systemd_service:
      name: mariadb
      state: started
      enable: true

  - name: Habilitamos en ufw la conexion de mariadb
    community.general.ufw:
      rule: allow
      port: '3306'
      protocol: tcp
      direction: in


##  configuracion de la base de datos

- name: Creo la base de datos todo
  community.mysql.mysql_db:
    check_implicit_admin: true
    login_host: "{{hostvars[inventory_hostname].ansible_host}}"
    login_user: root
    login_password: dbadmin
    name: todo
    state: import
    target: ./files/todo.sql
  delegate_to: localhost
  connection: local




